# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14.1-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: update-npm
          command:  'sudo npm install -g npm@latest'
      # Download and cache dependencies
      - restore_cache:
      # special step to restore the dependency cache
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache
      - run: 
          name: install-npm-globally
          command:  'sudo npm install -g @angular/cli lerna'
      - run: 
          name: install-lerna-packages-dependency
          command:  'sudo lerna bootstrap'
      - save_cache:
          key:  dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./packages/**/node_modules/        
      # run tests!
      - run:
          name: npm-angular-test
          command:  'sudo npm run docker:ui:test --watch=false --progress=false --browsers=ChromeHeadlessCI'